#!/bin/sh
cd "${0%/*}" || exit                                # Run from this directory
. ${WM_PROJECT_DIR:?}/bin/tools/RunFunctions        # Tutorial run functions
#------------------------------------------------------------------------------

runApplication blockMesh

runApplication surfaceFeatureExtract

runApplication decomposePar

runParallel snappyHexMesh -overwrite

runApplication reconstructParMesh -constant

rm -rf processor*

runApplication renumberMesh -overwrite

touch aero.foam




#------------------------------------------------------------------------------
